service: my-serverless-graphql-api
ss-graphql-api

provider:
  name: tencent
  runtime: Nodejs12.16

plugins:
  - serverless-tencent-scf

inputs:
  src: ./
  handler: sls.main_handler
  region: ap-beijing
  runtime: Nodejs12.16
  memorySize: 128
  timeout: 3
  environment:
    variables:
      DATABASE_HOST: {DATABASE_HOST}
      DATABASE_PORT: {DATABASE_PORT}
      DATABASE_USER: {DATABASE_USER}
      DATABASE_PASSWORD: "{DATABASE_PASSWORD}"
      DATABASE_NAME: {DATABASE_NAME}
  events: 
    - apigw: 
        parameters: 
          protocols: 
            - http
            - https
          environment: release
          endpoints: 
            - path: /
              method: POST
