component: scf
name: my-serverless-graphql-api

inputs:
  src: ./
  handler: sls.main_handler
  region: ap-beijing
  runtime: Nodejs12.16
  memorySize: 128
  timeout: 3
  events: 
    - apigw: 
        parameters: 
          protocols: 
            - http
            - https
          environment: release
          endpoints: 
            - path: /
              method: POST
