name: Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    name: Deploy
    steps:
    - uses: actions/checkout@v2

    - uses: bahmutov/npm-install@v1
      with:
        install-command: yarn --frozen-lockfile --silent

    - uses: cschleiden/replace-tokens@v1
      with:
        tokenPrefix: '{'
        tokenSuffix: '}'
        files: '["serverless.yml"]'
      env:
        DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
        DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
        DATABASE_USER: ${{ secrets.DATABASE_USER }}
        DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        DATABASE_NAME: ${{ secrets.DATABASE_NAME }}

    - name: Make env
      run: |
        echo ${{ secrets.TENCENT_APP_ID }} >> .env
        echo ${{ secrets.TENCENT_SECRET_ID }} >> .env
        echo ${{ secrets.TENCENT_SECRET_KEY }} >> .env
        echo ${{ secrets.TENCENT_TOKEN }} >> .env

    - name: Deploy
      run: |
        npx serverless deploy
