name: Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    name: Deploy
    steps:
    - uses: actions/checkout@v2

    - uses: bahmutov/npm-install@v1
      with:
        install-command: yarn --frozen-lockfile --silent

    - uses: cschleiden/replace-tokens@v1
      with:
        tokenPrefix: '{'
        tokenSuffix: '}'
        files: '["serverless.yml"]'
      env:
        DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
        DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
        DATABASE_USER: ${{ secrets.DATABASE_USER }}
        DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        DATABASE_NAME: ${{ secrets.DATABASE_NAME }}

    # - name: serverless deploy
    #   uses: serverless/github-action@master
    #   with:
    #     args: deploy
    #   env:
    #     TENCENT_APP_ID: ${{ secrets.TENCENT_APP_ID }}
    #     TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
    #     TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}
    #     TENCENT_TOKEN: ${{ secrets.TENCENT_TOKEN }}

    - name: Serverless Deploy
      uses: tegud/serverless-github-action@1.52.0
      with:
        command: deploy
      env:
        TENCENT_APP_ID: ${{ secrets.TENCENT_APP_ID }}
        TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
        TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}
        TENCENT_TOKEN: ${{ secrets.TENCENT_TOKEN }}
